### ISSUE TITLE
Declaration feedback/validation structure?

### ISSUE THREAD

**Issue by inverno** [hrishiballal/flight-declaration-protocol-development#9]
Hi,
Sorry for waking up on the eve of a live discussion :)
I would expect this protocol to have two main parts, the declaration and the feedback to the declaration, such as the validation errors.
Currently, to represent the feedback I only see the error section, which only allows one error and generally doesn't seem powerful enough for such a central role.
Regardless of further enrichment to the error parameter, I fear that adopting a symmetric message structure for a very asymmetric protocol (declaration-validation) is going to be more painful than its worth.

**Comment by hrishiballal** [comment]
Hi @inverno Thank you for your note. I agree that having a single error is not that useful but it is a start, so can you suggest some other errors please? We can add to the protcol then. 

Secondly I have opened #11 to track the feedback section. Can you let me know there what exactly you want detailed there?

**Comment by hrishiballal** [comment]
I agree re the synchronous and asynchronous nature of this work the declarations will be used both ways: 
1. To declare future flights (e.g. what is my scheudle for tomorrow) as in any airport, metro, bus stop etc. Although it is a very good question whether we should use GTFS for something like that. and to 
2. Manage schedules right before flying (i.e. request changes, cancel flights etc.) 

I think that primarily it is to be used as a data store to record flights before during and after the flight. Also a declaration can serve as a additional data point in case of a incident to check for e.g. if the flight is indeed taking the course it has declared etc.

**Comment by inverno** [comment]
I'll comment & contribute over at #11
